# Generated by Django 2.0.8 on 2019-12-29 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MultiChoiceQuestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(verbose_name='题目')),
                ('optionA', models.CharField(max_length=255, verbose_name='A选项')),
                ('optionB', models.CharField(max_length=255, verbose_name='B选项')),
                ('optionC', models.CharField(max_length=255, verbose_name='C选项')),
                ('optionD', models.CharField(max_length=255, verbose_name='D选项')),
                ('answer', models.CharField(choices=[('A', 'A'), ('A,B', 'A,B'), ('A,C', 'A,C'), ('A,D', 'A,D'), ('A,B,C', 'A,B,C'), ('A,B,D', 'A,B,D'), ('A,C,D', 'A,C,D'), ('A,B,C,D', 'A,B,C,D'), ('B', 'B'), ('B,C', 'B,C'), ('B,D', 'B,D'), ('B,C,D', 'B,C,D'), ('C', 'C'), ('C,D', 'C,D'), ('D', 'D')], max_length=10, verbose_name='答案')),
                ('score', models.IntegerField(default=2, verbose_name='分数')),
            ],
            options={
                'verbose_name': '多项选择题库',
                'verbose_name_plural': '多项选择题库',
            },
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='编号')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('sex', models.CharField(choices=[('男', '男'), ('女', '女')], default='男', max_length=4, verbose_name='性别')),
                ('dept', models.CharField(choices=[('总体室', '总体室'), ('软件室', '软件室'), ('设备室', '设备室'), ('管控室', '管控室'), ('保障室', '保障室')], default=None, max_length=20, verbose_name='部门')),
                ('password', models.CharField(default='111111', max_length=20, verbose_name='密码')),
            ],
            options={
                'verbose_name': '施训人',
                'verbose_name_plural': '施训人',
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examtime', models.DateTimeField()),
                ('mid', models.ManyToManyField(to='exam.MultiChoiceQuestion')),
            ],
            options={
                'verbose_name': '试卷',
                'verbose_name_plural': '试卷',
            },
        ),
        migrations.CreateModel(
            name='SingleChoiceQuestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(verbose_name='题目')),
                ('optionA', models.CharField(max_length=255, verbose_name='A选项')),
                ('optionB', models.CharField(max_length=255, verbose_name='B选项')),
                ('optionC', models.CharField(max_length=255, verbose_name='C选项')),
                ('optionD', models.CharField(max_length=255, verbose_name='D选项')),
                ('answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=10, verbose_name='答案')),
                ('score', models.IntegerField(default=1, verbose_name='分数')),
            ],
            options={
                'verbose_name': '单项选择题库',
                'verbose_name_plural': '单项选择题库',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='编号')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('sex', models.CharField(choices=[('男', '男'), ('女', '女')], default='男', max_length=4, verbose_name='性别')),
                ('dept', models.CharField(choices=[('总体室', '总体室'), ('软件室', '软件室'), ('设备室', '设备室'), ('管控室', '管控室'), ('保障室', '保障室')], default=None, max_length=20, verbose_name='部门')),
                ('password', models.CharField(default='111111', max_length=20, verbose_name='密码')),
            ],
            options={
                'verbose_name': '受训人',
                'verbose_name_plural': '受训人',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='科目编号')),
                ('title', models.CharField(max_length=50, verbose_name='科目名')),
            ],
            options={
                'verbose_name': '科目',
                'verbose_name_plural': '科目',
            },
        ),
        migrations.AddField(
            model_name='singlechoicequestion',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Subject'),
        ),
        migrations.AddField(
            model_name='paper',
            name='sid',
            field=models.ManyToManyField(to='exam.SingleChoiceQuestion'),
        ),
        migrations.AddField(
            model_name='paper',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Subject'),
        ),
        migrations.AddField(
            model_name='paper',
            name='tid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Officer'),
        ),
        migrations.AddField(
            model_name='multichoicequestion',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Subject'),
        ),
    ]
