# Generated by Django 2.0.8 on 2019-12-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='password',
            field=models.CharField(default='123456', max_length=20, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
