# Generated by Django 2.0.8 on 2019-12-30 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_paper_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
                ('sid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='exam.Student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Subject')),
            ],
            options={
                'verbose_name': '成绩',
                'verbose_name_plural': '成绩',
                'db_table': 'grade',
            },
        ),
    ]
