# Generated by Django 2.0.8 on 2020-01-04 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_auto_20191230_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='examperiod',
            field=models.IntegerField(default=45, verbose_name='考试时长'),
        ),
    ]
