# Generated by Django 2.0.8 on 2020-01-04 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_paperrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paperrecord',
            name='paperid',
        ),
        migrations.AddField(
            model_name='paperrecord',
            name='paper_title',
            field=models.CharField(default='测试', max_length=50, verbose_name='试卷名'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='title',
            field=models.CharField(default='测试', max_length=50, verbose_name='试卷名'),
        ),
    ]
