# Generated by Django 2.0.8 on 2020-01-04 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_auto_20200104_1506'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaperRecord',
        ),
    ]
