# Generated by Django 2.0.8 on 2020-01-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_paperrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paperrecord',
            name='answerList',
        ),
        migrations.AddField(
            model_name='paperrecord',
            name='answer_mc',
            field=models.CharField(default='', max_length=255, verbose_name='多选记录'),
        ),
        migrations.AddField(
            model_name='paperrecord',
            name='answer_sc',
            field=models.CharField(default='', max_length=255, verbose_name='单选记录'),
        ),
    ]
