# Generated by Django 2.0.8 on 2020-01-04 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_auto_20200104_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperrecord',
            name='stu_id',
            field=models.CharField(max_length=20, verbose_name='学生编号'),
        ),
    ]
