# Generated by Django 2.0.8 on 2020-01-04 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_auto_20200104_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paperrecord',
            name='answerList',
        ),
        migrations.RemoveField(
            model_name='paperrecord',
            name='paperid',
        ),
        migrations.RemoveField(
            model_name='paperrecord',
            name='stu_id',
        ),
    ]
