# Generated by Django 2.0.8 on 2020-01-04 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_auto_20200104_1453'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaperRecord',
        ),
    ]
